### ISSUE TITLE
Allow building with existing LiteCore checkout

### ISSUE THREAD

**Issue by snej** [couchbaselabs/cblite#1]
The `build.sh` script always checks out and builds LiteCore. It would be convenient for those already developing with LiteCore if it could use an existing LiteCore checkout; something like

`./build.sh --litecore /stuff/couchbase-lite-core`

**Comment by borrrden** [comment]
What if you had specified a different branch than the one you were working on in the other directory?  You could get this functionality now by using symlinks.

**Comment by borrrden** [comment]
Now that there is an actual submodule here, this probably cannot be done anymore.
