### ISSUE TITLE
Update replicator API calls for compatibility with latest LiteCore

### ISSUE THREAD

**Issue by saleembasit** [couchbaselabs/cblite#4]
Hi,

I have this error when building the tool;

```
...
[100%] Building CXX object CMakeFiles/cblite.dir/litecp/RemoteEndpoint.cc.o
[100%] Building CXX object CMakeFiles/cblite.dir/vendor/linenoise-ng/src/ConvertUTF.cpp.o
[100%] Building CXX object CMakeFiles/cblite.dir/vendor/linenoise-ng/src/linenoise.cpp.o
/root/cblite/litecp/DBEndpoint.cc:276:12: error: no member named 'onDocumentEnded' in 'C4ReplicatorParameters'
    params.onDocumentEnded = [](C4Replicator *repl,
    ~~~~~~ ^
1 error generated.
CMakeFiles/cblite.dir/build.make:302: recipe for target 'CMakeFiles/cblite.dir/litecp/DBEndpoint.cc.o' failed
make[3]: *** [CMakeFiles/cblite.dir/litecp/DBEndpoint.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:117: recipe for target 'CMakeFiles/cblite.dir/all' failed
make[2]: *** [CMakeFiles/cblite.dir/all] Error 2
CMakeFiles/Makefile2:129: recipe for target 'CMakeFiles/cblite.dir/rule' failed
make[1]: *** [CMakeFiles/cblite.dir/rule] Error 2
Makefile:175: recipe for target 'cblite' failed
make: *** [cblite] Error 2
```

I have issued these commands;

```
$ git clone https://github.com/couchbaselabs/cblite.git
$ cd cblite
$ ./build.sh
```

The OS is Debian 9 64-bit.

Note, I have built custom libc++ using [https://stackoverflow.com/a/43769803](https://stackoverflow.com/a/43769803).

Regards

**Comment by saleembasit** [comment]
Hi,

OK, seems like its a problem with LiteCore. I have tried using release/CBL2.1.x branch, and it worked.

Sorry for inconvenience.

Should this issue be closed?

**Comment by snej** [comment]
Yeah, the LiteCore C API is not stable and can change incompatibly during development. Now that the tool is in a separate repo, its revisions need to be tied to specific LiteCore revisions somehow ... the obvious way would be LiteCore as a submodule, but @borrrden had some valid reasons for not doing it that way, IIRC...
